sudo: false

notifications:
  email:
    - evantahler@gmail.com
language: node_js
node_js:
  - "0.10"
  # - "0.11"

branches:
  only:
    - master
services:
  - redis-server
# before_script:
notifications:
